version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
